export const projetos = [
  {
    nomeProjeto: 'lar botoeira de emergência',
    descricao: 'Instalar boteira de emergencia na EPPIR',
    justificativa: 'Segurança Operacional',
    valorTotalPrevisto: 100000.0,
    dataInicio: null,
    dataFim: null,
    poloId: 1,
    localId: 9,
    solicitanteId: 2,
    classificacaoId: 3,
    divisaoId: 1,
    gateId: null,
    tipoProjetoId: 2,
    demandaId: null,
    statusId: 1,
    prioridadeId: 3,
    complexidadeId: 2,
    dataInicioReal: null,
    dataFimReal: null,
    comentarios: null,
    deletado: false,
    item: 14,
    numero: null,
    responsavel_id: null,
    coordenador_id: null,
    elemento_pep: null,
  },
  {
    nomeProjeto:
      'lação de tanques de testes para poços com baixa produção ANB - carreta + automação',
    descricao: 'Adequação do ponto de medição de apropriação de Petroleo',
    justificativa:
      'Instalação de tanques de estes para poços com baixa produção Anambe',
    valorTotalPrevisto: 265000.0,
    dataInicio: null,
    dataFim: null,
    poloId: 1,
    localId: 14,
    solicitanteId: 2,
    classificacaoId: 2,
    divisaoId: 1,
    gateId: null,
    tipoProjetoId: 2,
    demandaId: null,
    statusId: 1,
    prioridade_id: 3,
    complexidade_id: 3,
    dataInicioReal: null,
    dataFimReal: null,
    comentarios: null,
    deletado: false,
    item: 17,
    numero: null,
    responsavel_id: null,
    coordenador_id: null,
    elemento_pep: null,
  },
  {
    nomeProjeto:
      'LADO - Transferência de fluido dos tanques por carreta de Anambé',
    descricao:
      'Projeto para Transferência de fluido dos tanques de teste da Estação Coletora de Anambé através de comissionamento de linha em conjunto de bomba de recalque para injeção de óleo no oleoduto ANB/FU',
    justificativa:
      'Com o aumento das intervenções e modificações dos métodos de elevação do campo de anambé, a tendência é que o volume de testes assim como a quantidade de m³ de fluido destinado aos tanques de teste aumente consideravelmente. Desta forma a Diretoria Operacional solicitou a abertura de Card para injeção dos fluidos dos tanques de teste no oleoduto ANB/FU.',
    valorTotalPrevisto: 2000000.0,
    dataInicio: null,
    dataFim: null,
    poloId: 1,
    localId: 14,
    solicitanteId: 2,
    classificacaoId: 5,
    divisaoId: 1,
    gateId: null,
    tipoProjetoId: 2,
    demandaId: 1,
    statusId: 6,
    prioridade_id: 3,
    complexidade_id: 3,
    dataInicioReal: null,
    dataFimReal: null,
    comentarios: null,
    deletado: false,
    item: 18,
    numero: null,
    responsavel_id: null,
    coordenador_id: null,
    elemento_pep: null,
  },
  {
    nomeProjeto: '- Baia de Multiprodutos de Petróleo',
    descricao: 'Baia Multiprodutos de Petróleo',
    justificativa:
      'Permitir maior produtividade e segurança nas descargas de Petróleo.',
    valorTotalPrevisto: 300000.0,
    dataInicio: null,
    dataFim: null,
    poloId: 1,
    localId: 9,
    solicitanteId: 7,
    classificacaoId: 6,
    divisaoId: 3,
    gateId: null,
    tipoProjetoId: 2,
    demandaId: 1,
    statusId: 7,
    prioridade_id: 1,
    complexidade_id: 1,
    dataInicioReal: null,
    dataFimReal: null,
    comentarios: null,
    deletado: false,
    item: 19,
    numero: null,
    responsavel_id: null,
    coordenador_id: null,
    elemento_pep: null,
  },
  {
    nomeProjeto: 'é e EPFU - Adequação da câmara de PIG do oleoduto DN 8"',
    descricao: 'Adequação da camara de PIG do duto multifasico ANB/FU',
    justificativa: 'Atendimento a requisitos tecnicos e legais',
    valorTotalPrevisto: 400000.0,
    dataInicio: null,
    dataFim: null,
    poloId: 1,
    localId: 14,
    solicitanteId: 8,
    classificacaoId: 2,
    divisaoId: 1,
    gateId: null,
    tipoProjetoId: 2,
    demandaId: null,
    statusId: 1,
    prioridade_id: 3,
    complexidade_id: 2,
    dataInicioReal: null,
    dataFimReal: null,
    comentarios: null,
    deletado: false,
    item: 23,
    numero: null,
    responsavel_id: null,
    coordenador_id: null,
    elemento_pep: null,
  },
  {
    nomeProjeto:
      'lação/Substituição de sensores vibração/impacto dos compressores Pilar',
    descricao:
      'instalação de novos instrumentos de vibração e impacto nos compressores da EPPIR',
    justificativa: 'Segurança operacional',
    valorTotalPrevisto: 120000.0,
    dataInicio: null,
    dataFim: null,
    poloId: 1,
    localId: 11,
    solicitanteId: 2,
    classificacaoId: 5,
    divisaoId: 1,
    gateId: null,
    tipoProjetoId: 2,
    demandaId: null,
    statusId: 1,
    prioridade_id: 3,
    complexidade_id: 1,
    dataInicioReal: null,
    dataFimReal: null,
    comentarios: null,
    deletado: false,
    item: 24,
    numero: null,
    responsavel_id: null,
    coordenador_id: null,
    elemento_pep: null,
  },
  {
    nomeProjeto:
      'lação/Substituição de sensores vibração/impacto dos compressores Furado',
    descricao:
      'instalação de novos instrumentos de vibração e impacto nos compressores daECFU',
    justificativa: 'Segurança operacional',
    valorTotalPrevisto: 130000.0,
    dataInicio: null,
    dataFim: null,
    poloId: 1,
    localId: 19,
    solicitanteId: 2,
    classificacaoId: 5,
    divisaoId: 1,
    gateId: null,
    tipoProjetoId: 2,
    demandaId: null,
    statusId: 1,
    prioridade_id: 3,
    complexidade_id: 2,
    dataInicioReal: null,
    dataFimReal: null,
    comentarios: null,
    deletado: false,
    item: 25,
    numero: null,
    responsavel_id: null,
    coordenador_id: null,
    elemento_pep: null,
  },
  {
    nomeProjeto: '- Baia de Multiprodutos GNV/GNC',
    descricao:
      'Baia Multiprodutos: Gás Natural Veicular e Gás Natural Comprimido',
    justificativa:
      'Permitir abastecimento de GNV e Abastecimento de caminhões de GNC. Rota azul de coleta de Petróleo na Bahia.',
    valorTotalPrevisto: 300000.0,
    dataInicio: null,
    dataFim: null,
    poloId: 1,
    localId: 9,
    solicitanteId: 7,
    classificacaoId: 6,
    divisaoId: 3,
    gateId: null,
    tipoProjetoId: 2,
    demandaId: 1,
    statusId: 7,
    prioridade_id: 3,
    complexidade_id: 2,
    dataInicioReal: null,
    dataFimReal: null,
    comentarios: null,
    deletado: false,
    item: 28,
    numero: null,
    responsavel_id: null,
    coordenador_id: null,
    elemento_pep: null,
  },
  {
    nomeProjeto: '- Readequação de Linhas de Tubulação dos GEAs 66 e 05',
    descricao:
      'Adequação do sistema de by pass das FVs dos GEAs 05 e 66 - EPPIR',
    justificativa: 'Adequar o layout existente para atender a norma',
    valorTotalPrevisto: 280000.0,
    dataInicio: null,
    dataFim: null,
    poloId: 1,
    localId: 9,
    solicitanteId: 2,
    classificacaoId: 4,
    divisaoId: 1,
    gateId: null,
    tipoProjetoId: 2,
    demandaId: null,
    statusId: 1,
    prioridade_id: 1,
    complexidade_id: 2,
    dataInicioReal: null,
    dataFimReal: null,
    comentarios: null,
    deletado: false,
    item: 29,
    numero: null,
    responsavel_id: null,
    coordenador_id: null,
    elemento_pep: null,
  },
  {
    nomeProjeto: 'ituição de válvula bean por motoválvula (12 cavalotes)',
    descricao: '',
    justificativa: '',
    valorTotalPrevisto: 0.0,
    dataInicio: null,
    dataFim: null,
    poloId: 1,
    localId: 16,
    solicitanteId: 2,
    classificacaoId: 5,
    divisaoId: 1,
    gateId: null,
    tipoProjetoId: 2,
    demandaId: null,
    statusId: 1,
    prioridade_id: 1,
    complexidade_id: 1,
    dataInicioReal: null,
    dataFimReal: null,
    comentarios: null,
    deletado: false,
    item: 59,
    numero: null,
    responsavel_id: null,
    coordenador_id: null,
    elemento_pep: null,
  },
  {
    nomeProjeto: 'de Carregamento de GLP',
    descricao:
      'Construção do Conjunto de carregamento B32F para GLP na Estação de Pilar',
    justificativa: 'Segurança Operacional',
    valorTotalPrevisto: 360000.0,
    dataInicio: null,
    dataFim: null,
    poloId: 1,
    localId: 12,
    solicitanteId: 2,
    classificacaoId: 5,
    divisaoId: 3,
    gateId: null,
    tipoProjetoId: 2,
    demandaId: null,
    statusId: 1,
    prioridade_id: 3,
    complexidade_id: 1,
    dataInicioReal: null,
    dataFimReal: null,
    comentarios: null,
    deletado: false,
    item: 32,
    numero: null,
    responsavel_id: null,
    coordenador_id: null,
    elemento_pep: null,
  },
  {
    nomeProjeto: 'ação de instrumentos na linha do flare',
    descricao: 'Realocação de instrumentos na linha do flare de Furado',
    justificativa: 'Atendimento a requisitos tecnicos e legais',
    valorTotalPrevisto: 60000.0,
    dataInicio: null,
    dataFim: null,
    poloId: 1,
    localId: 16,
    solicitanteId: 2,
    classificacaoId: 5,
    divisaoId: 1,
    gateId: null,
    tipoProjetoId: 2,
    demandaId: null,
    statusId: 8,
    prioridade_id: 3,
    complexidade_id: 1,
    dataInicioReal: null,
    dataFimReal: null,
    comentarios: null,
    deletado: false,
    item: 33,
    numero: null,
    responsavel_id: null,
    coordenador_id: null,
    elemento_pep: null,
  },
  {
    nomeProjeto: 's de Amostra de Óleo CSMC-17',
    descricao:
      'Instalação de pontos de amostra de óleo em diferentes elevações no tanque',
    justificativa: 'Atendimento a requisitos tecnicos e legais',
    valorTotalPrevisto: 90000.0,
    dataInicio: null,
    dataFim: null,
    poloId: 1,
    localId: 8,
    solicitanteId: 8,
    classificacaoId: 2,
    divisaoId: 1,
    gateId: null,
    tipoProjetoId: 2,
    demandaId: null,
    statusId: 8,
    prioridade_id: 3,
    complexidade_id: 2,
    dataInicioReal: null,
    dataFimReal: null,
    comentarios: null,
    deletado: false,
    item: 34,
    numero: null,
    responsavel_id: null,
    coordenador_id: null,
    elemento_pep: null,
  },
  {
    nomeProjeto: 's de Amostra de Óleo EPPIR',
    descricao:
      'Instalação de pontos de amostra de óleo em diferentes elevações no tanque',
    justificativa: 'Atendimento a requisitos tecnicos e legais',
    valorTotalPrevisto: 70000.0,
    dataInicio: null,
    dataFim: null,
    poloId: 1,
    localId: 9,
    solicitanteId: 8,
    classificacaoId: 2,
    divisaoId: 1,
    gateId: null,
    tipoProjetoId: 2,
    demandaId: null,
    statusId: 8,
    prioridade_id: 3,
    complexidade_id: 2,
    dataInicioReal: null,
    dataFimReal: null,
    comentarios: null,
    deletado: false,
    item: 35,
    numero: null,
    responsavel_id: null,
    coordenador_id: null,
    elemento_pep: null,
  },
  {
    nomeProjeto: '- Caixa API',
    descricao:
      'Instalação de LSHH e LT no compatimento de oleo da caixa API da EPPIR',
    justificativa:
      'Necessario a implantação de LSHH assim como um medidor LT tipo radar para maior confiabilidade na leitura de nivel da caixa API da EPPIR',
    valorTotalPrevisto: 300000.0,
    dataInicio: null,
    dataFim: null,
    poloId: 1,
    localId: 9,
    solicitanteId: 5,
    classificacaoId: 5,
    divisaoId: 1,
    gateId: null,
    tipoProjetoId: 2,
    demandaId: null,
    statusId: 1,
    prioridade_id: 3,
    complexidade_id: 2,
    dataInicioReal: null,
    dataFimReal: null,
    comentarios: null,
    deletado: false,
    item: 36,
    numero: null,
    responsavel_id: null,
    coordenador_id: null,
    elemento_pep: null,
  },
  {
    nomeProjeto: 's de Amostra de Gás  EPFU',
    descricao: 'Instalação dos pontos de amostra de gás da Estação de Furado',
    justificativa: 'Atendimento a requisitos tecnicos e legais',
    valorTotalPrevisto: 100000.0,
    dataInicio: null,
    dataFim: null,
    poloId: 1,
    localId: 16,
    solicitanteId: 8,
    classificacaoId: 2,
    divisaoId: 1,
    gateId: null,
    tipoProjetoId: 2,
    demandaId: null,
    statusId: 8,
    prioridade_id: 1,
    complexidade_id: 1,
    dataInicioReal: null,
    dataFimReal: null,
    comentarios: null,
    deletado: false,
    item: 39,
    numero: null,
    responsavel_id: null,
    coordenador_id: null,
    elemento_pep: null,
  },
  {
    nomeProjeto: "s de Amostra de Óleo EPFU (2 Tq's)",
    descricao: 'Instalação de pontos de amostra de óleo ',
    justificativa: 'Atendimento a requisitos tecnicos e legais',
    valorTotalPrevisto: 70000.0,
    dataInicio: null,
    dataFim: null,
    poloId: 1,
    localId: 9,
    solicitanteId: 8,
    classificacaoId: 2,
    divisaoId: 1,
    gateId: null,
    tipoProjetoId: 2,
    demandaId: null,
    statusId: 8,
    prioridade_id: 1,
    complexidade_id: 1,
    dataInicioReal: null,
    dataFimReal: null,
    comentarios: null,
    deletado: false,
    item: 40,
    numero: null,
    responsavel_id: null,
    coordenador_id: null,
    elemento_pep: null,
  },
  {
    nomeProjeto: 's de Amostra de Óleo SMC-12',
    descricao:
      'Instalação de pontos de amostra de óleo em diferentes elevações no tanque',
    justificativa: 'Atendimento a requisitos tecnicos e legais',
    valorTotalPrevisto: 65000.0,
    dataInicio: null,
    dataFim: null,
    poloId: 1,
    localId: 13,
    solicitanteId: 8,
    classificacaoId: 2,
    divisaoId: 1,
    gateId: null,
    tipoProjetoId: 2,
    demandaId: null,
    statusId: 8,
    prioridade_id: 3,
    complexidade_id: 1,
    dataInicioReal: null,
    dataFimReal: null,
    comentarios: null,
    deletado: false,
    item: 41,
    numero: null,
    responsavel_id: null,
    coordenador_id: null,
    elemento_pep: null,
  },
  {
    nomeProjeto: '- Adequação Câmara de PIG',
    descricao: 'Adequação da Camara de PIG de Paru a NBR 16831/2015',
    justificativa: 'Atendimento a requisitos tecnicos e legais',
    valorTotalPrevisto: 100000.0,
    dataInicio: null,
    dataFim: null,
    poloId: 1,
    localId: 6,
    solicitanteId: 8,
    classificacaoId: 2,
    divisaoId: 1,
    gateId: null,
    tipoProjetoId: 2,
    demandaId: null,
    statusId: 1,
    prioridade_id: 3,
    complexidade_id: 1,
    dataInicioReal: null,
    dataFimReal: null,
    comentarios: null,
    deletado: false,
    item: 42,
    numero: null,
    responsavel_id: null,
    coordenador_id: null,
    elemento_pep: null,
  },
  {
    nomeProjeto: 's de Amostra de Óleo ANB',
    descricao:
      'Instalação de pontos de amostra de óleo em diferentes elevações no tanque',
    justificativa: 'Atendimento a requisitos tecnicos e legais',
    valorTotalPrevisto: 100000.0,
    dataInicio: null,
    dataFim: null,
    poloId: 1,
    localId: 14,
    solicitanteId: 8,
    classificacaoId: 2,
    divisaoId: 1,
    gateId: null,
    tipoProjetoId: 2,
    demandaId: null,
    statusId: 8,
    prioridade_id: 3,
    complexidade_id: 1,
    dataInicioReal: null,
    dataFimReal: null,
    comentarios: null,
    deletado: false,
    item: 43,
    numero: null,
    responsavel_id: null,
    coordenador_id: null,
    elemento_pep: null,
  },
  {
    nomeProjeto: 'la de retenção na linha tronco do GEA da EPFU',
    descricao:
      'Instalação de válvula de retenção na linha tronco do GEA de Furado',
    justificativa: 'Segurança Operacional',
    valorTotalPrevisto: 20000.0,
    dataInicio: null,
    dataFim: null,
    poloId: 1,
    localId: 16,
    solicitanteId: 2,
    classificacaoId: 5,
    divisaoId: 1,
    gateId: null,
    tipoProjetoId: 2,
    demandaId: null,
    statusId: 1,
    prioridade_id: 3,
    complexidade_id: 1,
    dataInicioReal: null,
    dataFimReal: null,
    comentarios: null,
    deletado: false,
    item: 44,
    numero: null,
    responsavel_id: null,
    coordenador_id: null,
    elemento_pep: null,
  },
  {
    nomeProjeto: 's de Amostra de Gás Pilar',
    descricao: 'Instalação dos pontos de amostra de gás da Estação de Pilar',
    justificativa: 'Atendimento a requisitos tecnicos e legais',
    valorTotalPrevisto: 100000.0,
    dataInicio: null,
    dataFim: null,
    poloId: 1,
    localId: 9,
    solicitanteId: 2,
    classificacaoId: 2,
    divisaoId: 1,
    gateId: null,
    tipoProjetoId: 2,
    demandaId: null,
    statusId: 8,
    prioridade_id: 3,
    complexidade_id: 1,
    dataInicioReal: null,
    dataFimReal: null,
    comentarios: null,
    deletado: false,
    item: 45,
    numero: null,
    responsavel_id: null,
    coordenador_id: null,
    elemento_pep: null,
  },
  {
    nomeProjeto: 'lação de chaves de nível alto/baixo Tratadores de Óleo',
    descricao:
      'Instalação das chaves de nivel alta/baixa dos tratadores de oleo da estação de pilar',
    justificativa: 'Atendimento a requisitos tecnicos e legais',
    valorTotalPrevisto: 280000.0,
    dataInicio: null,
    dataFim: null,
    poloId: 1,
    localId: 9,
    solicitanteId: 2,
    classificacaoId: 5,
    divisaoId: 1,
    gateId: null,
    tipoProjetoId: 2,
    demandaId: null,
    statusId: 1,
    prioridade_id: 1,
    complexidade_id: 1,
    dataInicioReal: null,
    dataFimReal: null,
    comentarios: null,
    deletado: false,
    item: 46,
    numero: null,
    responsavel_id: null,
    coordenador_id: null,
    elemento_pep: null,
  },
  {
    nomeProjeto: 'LADO - Alimentação do cooler dos switches',
    descricao: 'Alimentação do cooler dos switches',
    justificativa: 'Segurança operacional',
    valorTotalPrevisto: 345538.18,
    dataInicio: null,
    dataFim: null,
    poloId: 1,
    localId: 16,
    solicitanteId: 2,
    classificacaoId: 4,
    divisaoId: 1,
    gateId: null,
    tipoProjetoId: 2,
    demandaId: null,
    statusId: 6,
    prioridade_id: 3,
    complexidade_id: 1,
    dataInicioReal: null,
    dataFimReal: null,
    comentarios: null,
    deletado: false,
    item: 47,
    numero: null,
    responsavel_id: null,
    coordenador_id: null,
    elemento_pep: null,
  },
  {
    nomeProjeto: 'Recuperação do Talude - Hidrante 32',
    descricao:
      'Necessidade de recuperação de Talude na área do Hidrante 32 de Furado',
    justificativa: 'Segurança Operacional e Visita do CBM em 25.03.2022',
    valorTotalPrevisto: 85123.0,
    dataInicio: null,
    dataFim: null,
    poloId: 1,
    localId: 16,
    solicitanteId: 5,
    classificacaoId: 3,
    divisaoId: 1,
    gateId: null,
    tipoProjetoId: 2,
    demandaId: null,
    statusId: 5,
    prioridade_id: 3,
    complexidade_id: 1,
    dataInicioReal: null,
    dataFimReal: null,
    comentarios: null,
    deletado: false,
    item: 50,
    numero: 7,
    responsavel_id: null,
    coordenador_id: null,
    elemento_pep: null,
  },
  {
    nomeProjeto:
      'xamento da Contra-pressão de ANB -Oleoduto ANB/FUR 2 (10 km de duto)',
    descricao: '',
    justificativa: '',
    valorTotalPrevisto: 8000000.0,
    dataInicio: null,
    dataFim: null,
    poloId: 1,
    localId: 16,
    solicitanteId: 2,
    classificacaoId: 6,
    divisaoId: 2,
    gateId: null,
    tipoProjetoId: 2,
    demandaId: null,
    statusId: 1,
    prioridade_id: 1,
    complexidade_id: 2,
    dataInicioReal: null,
    dataFimReal: null,
    comentarios: null,
    deletado: false,
    item: 51,
    numero: null,
    responsavel_id: null,
    coordenador_id: null,
    elemento_pep: null,
  },
  {
    nomeProjeto: 'Paru - Travessia do Rio Coruripe',
    descricao:
      'Projeto para travessia do duto Furado/Robalo entre os leitos do Rio Coruripe',
    justificativa:
      'O duto existente está erudindo e precisa de um novo projeto.',
    valorTotalPrevisto: 10000000.0,
    dataInicio: null,
    dataFim: null,
    poloId: 1,
    localId: 6,
    solicitanteId: 5,
    classificacaoId: 4,
    divisaoId: 1,
    gateId: 1,
    tipoProjetoId: 2,
    demandaId: null,
    statusId: 3,
    prioridade_id: 3,
    complexidade_id: 3,
    dataInicioReal: null,
    dataFimReal: null,
    comentarios: null,
    deletado: false,
    item: 6,
    numero: 8,
    responsavel_id: 3,
    coordenador_id: null,
    elemento_pep: 'OGAL.22008.FS',
  },
  {
    nomeProjeto: 'EPPIR - Relocação de Linhas',
    descricao:
      'Relocação de linhas dos poços e instalação de novas linhas de tie-in de utilidades e GN para UTE e GNL – Áreas da UPGN, UTE e GNL– Linhas de Produção Poços PIR 19 / PIR 79 / PIR 253',
    justificativa:
      'Liberar áreas da UTE e GNL para início da terraplanagem e posterior construção e montagem',
    valorTotalPrevisto: 8000000.0,
    dataInicio: null,
    dataFim: null,
    poloId: 1,
    localId: 3,
    solicitanteId: 4,
    classificacaoId: 6,
    divisaoId: 1,
    gateId: 1,
    tipoProjetoId: 2,
    demandaId: 1,
    statusId: 3,
    prioridade_id: 3,
    complexidade_id: 2,
    dataInicioReal: null,
    dataFimReal: null,
    comentarios: null,
    deletado: false,
    item: 13,
    numero: 9,
    responsavel_id: 2,
    coordenador_id: null,
    elemento_pep: 'OGAL.22009.PA',
  },
  {
    nomeProjeto: 'ação da PV-624014',
    descricao:
      'Realizar estudo para adequação da PV-624014 às novas condições operacionais: vazão mínima: 100k m3/d;',
    justificativa:
      'Adequar a operação da PV-14 para o novo cenário de escoamento de gás para a TAG.',
    valorTotalPrevisto: 0.0,
    dataInicio: null,
    dataFim: null,
    poloId: 1,
    localId: 4,
    solicitanteId: 2,
    classificacaoId: null,
    divisaoId: null,
    gateId: null,
    tipoProjetoId: 1,
    demandaId: 1,
    statusId: 5,
    prioridade_id: 1,
    complexidade_id: 2,
    dataInicioReal: null,
    dataFimReal: null,
    comentarios: null,
    deletado: false,
    item: 52,
    numero: null,
    responsavel_id: null,
    coordenador_id: null,
    elemento_pep: null,
  },
  {
    nomeProjeto: 'ação da unidade de desidratação de Gás Natural  (UDG)',
    descricao: '',
    justificativa: '',
    valorTotalPrevisto: 0.0,
    dataInicio: null,
    dataFim: null,
    poloId: 1,
    localId: 16,
    solicitanteId: 2,
    classificacaoId: 5,
    divisaoId: 1,
    gateId: null,
    tipoProjetoId: 2,
    demandaId: null,
    statusId: 1,
    prioridade_id: 1,
    complexidade_id: 1,
    dataInicioReal: null,
    dataFimReal: null,
    comentarios: null,
    deletado: false,
    item: 53,
    numero: null,
    responsavel_id: null,
    coordenador_id: null,
    elemento_pep: null,
  },
  {
    nomeProjeto: 'lação de bomba Jockey no SCI - Pilar',
    descricao: '',
    justificativa: '',
    valorTotalPrevisto: 0.0,
    dataInicio: null,
    dataFim: null,
    poloId: 1,
    localId: 9,
    solicitanteId: 2,
    classificacaoId: 3,
    divisaoId: 1,
    gateId: null,
    tipoProjetoId: 2,
    demandaId: null,
    statusId: 1,
    prioridade_id: null,
    complexidade_id: null,
    dataInicioReal: null,
    dataFimReal: null,
    comentarios: null,
    deletado: false,
    item: 54,
    numero: null,
    responsavel_id: null,
    coordenador_id: null,
    elemento_pep: null,
  },
  {
    nomeProjeto: 'lação de bomba Jockey no SCI - Furado',
    descricao: '',
    justificativa: '',
    valorTotalPrevisto: 0.0,
    dataInicio: null,
    dataFim: null,
    poloId: 1,
    localId: 16,
    solicitanteId: 2,
    classificacaoId: 3,
    divisaoId: 1,
    gateId: null,
    tipoProjetoId: 2,
    demandaId: null,
    statusId: 1,
    prioridade_id: 1,
    complexidade_id: 1,
    dataInicioReal: null,
    dataFimReal: null,
    comentarios: null,
    deletado: false,
    item: 55,
    numero: null,
    responsavel_id: null,
    coordenador_id: null,
    elemento_pep: null,
  },
  {
    nomeProjeto: 'ria da malha de intertravamento dos vasos',
    descricao: '',
    justificativa: '',
    valorTotalPrevisto: 0.0,
    dataInicio: null,
    dataFim: null,
    poloId: 1,
    localId: 9,
    solicitanteId: 2,
    classificacaoId: 5,
    divisaoId: 1,
    gateId: null,
    tipoProjetoId: 2,
    demandaId: null,
    statusId: 1,
    prioridade_id: null,
    complexidade_id: null,
    dataInicioReal: null,
    dataFimReal: null,
    comentarios: null,
    deletado: false,
    item: 56,
    numero: null,
    responsavel_id: null,
    coordenador_id: null,
    elemento_pep: null,
  },
  {
    nomeProjeto: 'ria do IUGA para aumento de produção',
    descricao: '',
    justificativa: '',
    valorTotalPrevisto: 0.0,
    dataInicio: null,
    dataFim: null,
    poloId: 1,
    localId: 9,
    solicitanteId: 2,
    classificacaoId: 2,
    divisaoId: 1,
    gateId: null,
    tipoProjetoId: 2,
    demandaId: null,
    statusId: 1,
    prioridade_id: 1,
    complexidade_id: 1,
    dataInicioReal: null,
    dataFimReal: null,
    comentarios: null,
    deletado: false,
    item: 57,
    numero: null,
    responsavel_id: null,
    coordenador_id: null,
    elemento_pep: null,
  },
  {
    nomeProjeto: 'ção Catódica',
    descricao: '',
    justificativa: '',
    valorTotalPrevisto: 0.0,
    dataInicio: null,
    dataFim: null,
    poloId: 1,
    localId: 18,
    solicitanteId: 2,
    classificacaoId: 4,
    divisaoId: 1,
    gateId: null,
    tipoProjetoId: 2,
    demandaId: null,
    statusId: 1,
    prioridade_id: null,
    complexidade_id: null,
    dataInicioReal: null,
    dataFimReal: null,
    comentarios: null,
    deletado: false,
    item: 58,
    numero: null,
    responsavel_id: null,
    coordenador_id: null,
    elemento_pep: null,
  },
  {
    nomeProjeto: 'gem para armazenamento do Petróleo',
    descricao: '',
    justificativa: '',
    valorTotalPrevisto: 0.0,
    dataInicio: null,
    dataFim: null,
    poloId: 1,
    localId: 9,
    solicitanteId: 2,
    classificacaoId: 6,
    divisaoId: 3,
    gateId: null,
    tipoProjetoId: 2,
    demandaId: 1,
    statusId: 7,
    prioridade_id: 1,
    complexidade_id: 1,
    dataInicioReal: null,
    dataFimReal: null,
    comentarios: null,
    deletado: false,
    item: 60,
    numero: null,
    responsavel_id: null,
    coordenador_id: null,
    elemento_pep: null,
  },
  {
    nomeProjeto: 'ssia de Rio São Miguel',
    descricao: '',
    justificativa: '',
    valorTotalPrevisto: 0.0,
    dataInicio: null,
    dataFim: null,
    poloId: 1,
    localId: 18,
    solicitanteId: 2,
    classificacaoId: 4,
    divisaoId: 2,
    gateId: null,
    tipoProjetoId: 2,
    demandaId: null,
    statusId: 1,
    prioridade_id: null,
    complexidade_id: null,
    dataInicioReal: null,
    dataFimReal: null,
    comentarios: null,
    deletado: false,
    item: 61,
    numero: null,
    responsavel_id: null,
    coordenador_id: null,
    elemento_pep: null,
  },
  {
    nomeProjeto: 'no do vaso de produção - EGNA Quererá',
    descricao:
      'Retorno do vaso de produção da EGNA Quererá em conjunto do sistema de medição (EMED Operacional).',
    justificativa:
      'O retorno operacional do vaso de produção da EGNA Quererá permitirá a instalação de uma EMED para medição da produção da Estação, facilitando o processo de tomada de decisão em relação a abertura de poços e rodizio dos mesmo. O retorno de ambos os equipamentos permitiria um incremento da produção por possibilitar o retorno de passagem de pig nas linhas dos poços, além de identificar desvios no processo (queda de vazão).',
    valorTotalPrevisto: 0.0,
    dataInicio: null,
    dataFim: null,
    poloId: 2,
    localId: 17,
    solicitanteId: 2,
    classificacaoId: 5,
    divisaoId: 1,
    gateId: null,
    tipoProjetoId: 2,
    demandaId: 1,
    statusId: 7,
    prioridade_id: 1,
    complexidade_id: 1,
    dataInicioReal: null,
    dataFimReal: null,
    comentarios: null,
    deletado: false,
    item: 62,
    numero: null,
    responsavel_id: null,
    coordenador_id: null,
    elemento_pep: null,
  },
  {
    nomeProjeto:
      'Instalação de novo tramo de medição em paralelo à EMED FE-124402 de Pilar',
    descricao: '',
    justificativa: '',
    valorTotalPrevisto: 0.0,
    dataInicio: null,
    dataFim: null,
    poloId: 1,
    localId: 9,
    solicitanteId: 2,
    classificacaoId: null,
    divisaoId: 2,
    gateId: null,
    tipoProjetoId: 2,
    demandaId: null,
    statusId: 8,
    prioridade_id: 1,
    complexidade_id: 1,
    dataInicioReal: null,
    dataFimReal: null,
    comentarios: null,
    deletado: false,
    item: 63,
    numero: null,
    responsavel_id: null,
    coordenador_id: null,
    elemento_pep: null,
  },
  {
    nomeProjeto:
      'lação de novo tramo de medição em paralelo à EMED FE-SG-122101-02 ANB',
    descricao: '',
    justificativa: '',
    valorTotalPrevisto: 0.0,
    dataInicio: null,
    dataFim: null,
    poloId: 1,
    localId: 14,
    solicitanteId: 2,
    classificacaoId: null,
    divisaoId: 2,
    gateId: null,
    tipoProjetoId: 2,
    demandaId: null,
    statusId: 8,
    prioridade_id: 1,
    complexidade_id: 2,
    dataInicioReal: null,
    dataFimReal: null,
    comentarios: null,
    deletado: false,
    item: 64,
    numero: null,
    responsavel_id: null,
    coordenador_id: null,
    elemento_pep: null,
  },
  {
    nomeProjeto:
      'lação de novo tramo de medição para a saída do Gás dos Tratadores de Furado - FE-V-122201',
    descricao: '',
    justificativa: '',
    valorTotalPrevisto: 0.0,
    dataInicio: null,
    dataFim: null,
    poloId: 1,
    localId: 16,
    solicitanteId: 2,
    classificacaoId: null,
    divisaoId: 2,
    gateId: null,
    tipoProjetoId: 2,
    demandaId: null,
    statusId: 8,
    prioridade_id: 1,
    complexidade_id: 2,
    dataInicioReal: null,
    dataFimReal: null,
    comentarios: null,
    deletado: false,
    item: 65,
    numero: null,
    responsavel_id: null,
    coordenador_id: null,
    elemento_pep: null,
  },
  {
    nomeProjeto:
      'lação de novo tramo de medição em paralelo à EMED FE-SG-122101-01 FU',
    descricao: '',
    justificativa: '',
    valorTotalPrevisto: 0.0,
    dataInicio: null,
    dataFim: null,
    poloId: 1,
    localId: 16,
    solicitanteId: 2,
    classificacaoId: null,
    divisaoId: 2,
    gateId: null,
    tipoProjetoId: 2,
    demandaId: null,
    statusId: 8,
    prioridade_id: 1,
    complexidade_id: 2,
    dataInicioReal: null,
    dataFimReal: null,
    comentarios: null,
    deletado: false,
    item: 66,
    numero: null,
    responsavel_id: null,
    coordenador_id: null,
    elemento_pep: null,
  },
  {
    nomeProjeto: 'de Resfriamento TR-512401A',
    descricao:
      'Equipamento fora de operação há 2 anos. Aberto RTA e INSPLAN para normalizar funcionamento e automatizar os instrumentos na antiga operadora, contudo, foi identificada a inviabilidade de manutenir e optou-se por fazer a aquisição de um equipamento novo. Fabricação e montagem de toda a estrutura de sustentação com subsequente substituição do recheio.',
    justificativa: 'Otimização do sistema de resfriamento',
    valorTotalPrevisto: 0.0,
    dataInicio: null,
    dataFim: null,
    poloId: 1,
    localId: 12,
    solicitanteId: null,
    classificacaoId: 4,
    divisaoId: null,
    gateId: 2,
    tipoProjetoId: 2,
    demandaId: 1,
    statusId: 1,
    prioridade_id: 1,
    complexidade_id: 2,
    dataInicioReal: null,
    dataFimReal: null,
    comentarios: null,
    deletado: false,
    item: 67,
    numero: null,
    responsavel_id: null,
    coordenador_id: null,
    elemento_pep: null,
  },
  {
    nomeProjeto: 'ão da contrapressão em Parú',
    descricao: 'Análise crítica ou revalidação do projeto da PBR.',
    justificativa:
      'Um estudo para checar o escoamento no duto e também verificar se os equipamentos, válvulas de controle e demais instrumentos do sistema estariam adequados.',
    valorTotalPrevisto: 0.0,
    dataInicio: null,
    dataFim: null,
    poloId: 1,
    localId: 6,
    solicitanteId: 2,
    classificacaoId: null,
    divisaoId: null,
    gateId: null,
    tipoProjetoId: 1,
    demandaId: 1,
    statusId: 5,
    prioridade_id: 1,
    complexidade_id: 2,
    dataInicioReal: null,
    dataFimReal: null,
    comentarios: null,
    deletado: false,
    item: 68,
    numero: null,
    responsavel_id: null,
    coordenador_id: null,
    elemento_pep: null,
  },
  {
    nomeProjeto: 'ação técnica bombas Borets e Baker',
    descricao:
      'Avaliação técnica para compra das bombas de injeção de água produzida da Baker e Borets',
    justificativa: 'Necessidade de novas bombas nas estações de Pilar e Furado',
    valorTotalPrevisto: 0.0,
    dataInicio: null,
    dataFim: null,
    poloId: 1,
    localId: 27,
    solicitanteId: 2,
    classificacaoId: null,
    divisaoId: null,
    gateId: null,
    tipoProjetoId: 1,
    demandaId: 1,
    statusId: 5,
    prioridade_id: 1,
    complexidade_id: 1,
    dataInicioReal: null,
    dataFimReal: null,
    comentarios: null,
    deletado: false,
    item: 69,
    numero: null,
    responsavel_id: null,
    coordenador_id: null,
    elemento_pep: null,
  },
  {
    nomeProjeto: 'lo de CV da Válvula de controle de vazão - PTS',
    descricao:
      'Calculo de CV da válvula de controle de vazão da ETC Alagoinhas.',
    justificativa:
      'Válvula da Hitter apresentou problemas em seus internos, sendo necessário a troca dos mesmos e oportunizando uma melhora no calculo do CV.',
    valorTotalPrevisto: 0.0,
    dataInicio: null,
    dataFim: null,
    poloId: 2,
    localId: 26,
    solicitanteId: 2,
    classificacaoId: null,
    divisaoId: null,
    gateId: 6,
    tipoProjetoId: 1,
    demandaId: 1,
    statusId: 1,
    prioridade_id: null,
    complexidade_id: null,
    dataInicioReal: null,
    dataFimReal: null,
    comentarios: null,
    deletado: false,
    item: 70,
    numero: null,
    responsavel_id: null,
    coordenador_id: null,
    elemento_pep: null,
  },
  {
    nomeProjeto: '- Inibidor de Corrosão',
    descricao:
      'Instalação de bomba dosadora em conjunto de reservatório de fluido e sistema fotovoltaico para injeção de inibidor de corrosão na linha de 8" do poço ALS-39. O sistema deverá ficar locado na boia de Paru. ',
    justificativa:
      'Verificação do agravamento da corrosão interna da linha do poço ALS-39 até a Estação Coletora de Paru. ',
    valorTotalPrevisto: 0.0,
    dataInicio: null,
    dataFim: null,
    poloId: 1,
    localId: 6,
    solicitanteId: 2,
    classificacaoId: 5,
    divisaoId: 1,
    gateId: 2,
    tipoProjetoId: 2,
    demandaId: 1,
    statusId: 1,
    prioridade_id: 1,
    complexidade_id: 2,
    dataInicioReal: null,
    dataFimReal: null,
    comentarios: null,
    deletado: false,
    item: 71,
    numero: null,
    responsavel_id: null,
    coordenador_id: null,
    elemento_pep: null,
  },
  {
    nomeProjeto:
      'ferência de fluido dos tanques de teste da Estação Coletora de Anambé',
    descricao:
      'Projeto para Transferência de fluido dos tanques de teste da Estação Coletora de Anambé através de comissionamento de linha em conjunto de bomba de recalque para injeção de óleo no oleoduto ANB/FU',
    justificativa:
      'Com o aumento das intervenções e modificações dos métodos de elevação do campo de anambé, a tendência é que o volume de testes assim como a quantidade de m³ de fluido destinado aos tanques de teste aumente consideravelmente. Desta forma a Diretoria Operacional solicitou a abertura de Card para injeção dos fluidos dos tanques de teste no oleoduto ANB/FU.',
    valorTotalPrevisto: 0.0,
    dataInicio: null,
    dataFim: null,
    poloId: 1,
    localId: 14,
    solicitanteId: 2,
    classificacaoId: null,
    divisaoId: null,
    gateId: null,
    tipoProjetoId: 2,
    demandaId: 1,
    statusId: 6,
    prioridade_id: 1,
    complexidade_id: 2,
    dataInicioReal: null,
    dataFimReal: null,
    comentarios: null,
    deletado: false,
    item: 72,
    numero: null,
    responsavel_id: null,
    coordenador_id: null,
    elemento_pep: null,
  },
  {
    nomeProjeto: 'ma de Captação de Água Pluvial - Pilar',
    descricao:
      'Adequação do sistema de captação de água pluvial coletadas por meio de bueiros e calhas e que viajam por duto até a caixa API.',
    justificativa:
      'Água pluvial é destinada para caixa API através de dutos específicos que, quando direcionada a caixa API, aumenta o nível rapidamente em momentos de chuva. A água pluvial retorna ao processo através da caixa API, havendo um gasto energético nas bombas de recalque de água/óleo da caixa API, assim como nos TO´s, bomba Baker e Boosters em conjunto de aumento do consumo de produtos químicos.',
    valorTotalPrevisto: 0.0,
    dataInicio: null,
    dataFim: null,
    poloId: 1,
    localId: 9,
    solicitanteId: 2,
    classificacaoId: 3,
    divisaoId: 2,
    gateId: 6,
    tipoProjetoId: 1,
    demandaId: 1,
    statusId: 1,
    prioridade_id: 1,
    complexidade_id: 1,
    dataInicioReal: null,
    dataFimReal: null,
    comentarios: null,
    deletado: false,
    item: 73,
    numero: null,
    responsavel_id: null,
    coordenador_id: null,
    elemento_pep: null,
  },
  {
    nomeProjeto: 'ma de Captação de Água Pluvial - Furado',
    descricao:
      'Adequação do sistema de captação de água pluvial coletadas por meio de bueiros e calhas e que viajam por duto até a caixa API.',
    justificativa:
      'Água pluvial é destinada para caixa API através de dutos específicos que, quando direcionada a caixa API, aumenta o nível rapidamente em momentos de chuva. A água pluvial retorna ao processo através da caixa API, havendo um gasto energético nas bombas de recalque de água/óleo da caixa API, assim como nos TO´s, bomba Baker e Boosters em conjunto de aumento do consumo de produtos químicos.',
    valorTotalPrevisto: 0.0,
    dataInicio: null,
    dataFim: null,
    poloId: 1,
    localId: 16,
    solicitanteId: 2,
    classificacaoId: 3,
    divisaoId: 2,
    gateId: 6,
    tipoProjetoId: 1,
    demandaId: 1,
    statusId: 1,
    prioridade_id: 1,
    complexidade_id: 2,
    dataInicioReal: null,
    dataFimReal: null,
    comentarios: null,
    deletado: false,
    item: 74,
    numero: null,
    responsavel_id: null,
    coordenador_id: null,
    elemento_pep: null,
  },
  {
    nomeProjeto: 'os de água FT-125101A e FT-125101B',
    descricao:
      'Histórico: Equipamento é componente do sistema de injeção de água, porém, esses filtros nunca operaram na antiga operadora e efetivamente não entraram em operação dado que o projeto foi descontinuado. Escopo: Instalação de válvulas, fabricação de skids, recomposição de instrumentos e instalação do conjunto motor-bomba.',
    justificativa: 'ecuperação do sistema de filtragem',
    valorTotalPrevisto: 0.0,
    dataInicio: null,
    dataFim: null,
    poloId: 1,
    localId: 12,
    solicitanteId: null,
    classificacaoId: 4,
    divisaoId: null,
    gateId: 2,
    tipoProjetoId: 2,
    demandaId: 1,
    statusId: 1,
    prioridade_id: null,
    complexidade_id: null,
    dataInicioReal: null,
    dataFimReal: null,
    comentarios: null,
    deletado: false,
    item: 75,
    numero: null,
    responsavel_id: null,
    coordenador_id: null,
    elemento_pep: null,
  },
  {
    nomeProjeto: 'lar vaso Separador/Gasdry no BEL-1',
    descricao: 'Realizar instalação de vaso separador.',
    justificativa:
      'A medição de vazão de gás por placa de orifício no ponto UT-1210001 está incoerente, devido ao excesso de líquido que o poço está produzindo. A instalação do vaso nos permitirá estimar o potencial correto de produção de gás e líquido do poço.',
    valorTotalPrevisto: 0.0,
    dataInicio: null,
    dataFim: null,
    poloId: 1,
    localId: 22,
    solicitanteId: 3,
    classificacaoId: null,
    divisaoId: null,
    gateId: 2,
    tipoProjetoId: 2,
    demandaId: 1,
    statusId: 1,
    prioridade_id: 1,
    complexidade_id: 1,
    dataInicioReal: null,
    dataFimReal: null,
    comentarios: null,
    deletado: false,
    item: 76,
    numero: null,
    responsavel_id: null,
    coordenador_id: null,
    elemento_pep: null,
  },
  {
    nomeProjeto: 'tura da área destinada para produtos químicos',
    descricao:
      'Cobertura da área destinada para produtos químicos, óleos, graxas e tintas ao lado a unidade de compressão da EGNA Conceição.',
    justificativa:
      'Necessidade de cobertura para área destinada a armazenagem de produtos quimicos e etc. Há bacia de contenção construída na Estação sendo necessária a construção de cobertura para que não ocorra o enchimento da caixa coletora com água provinda da chuva, além de proteger contra intemperes climáticos os barris metálicos de óleo, graxas dentre outros.',
    valorTotalPrevisto: 0.0,
    dataInicio: null,
    dataFim: null,
    poloId: 2,
    localId: 2,
    solicitanteId: 2,
    classificacaoId: null,
    divisaoId: null,
    gateId: null,
    tipoProjetoId: 2,
    demandaId: 1,
    statusId: 6,
    prioridade_id: 1,
    complexidade_id: 2,
    dataInicioReal: null,
    dataFimReal: null,
    comentarios: null,
    deletado: false,
    item: 77,
    numero: null,
    responsavel_id: null,
    coordenador_id: null,
    elemento_pep: null,
  },
  {
    nomeProjeto: 'a de Purga',
    descricao:
      'Planta de Purga para realizar tratamento de poços em gás que produzem líquido e não possuem energia suficiente para carrear esse líquido para fora da coluna.',
    justificativa:
      'Método necessário para aumento de produção de poços de gás do Polo Tucano Sul, pelo fato que os mesmos vem decaindo a produção por conta da acumulação de líquido na coluna. A planta de purga iria auxiliar na descarga de líquido e incremento na produção de gás.',
    valorTotalPrevisto: 0.0,
    dataInicio: null,
    dataFim: null,
    poloId: 2,
    localId: 2,
    solicitanteId: null,
    classificacaoId: null,
    divisaoId: null,
    gateId: null,
    tipoProjetoId: 2,
    demandaId: 1,
    statusId: 2,
    prioridade_id: null,
    complexidade_id: null,
    dataInicioReal: null,
    dataFimReal: null,
    comentarios: null,
    deletado: false,
    item: 78,
    numero: null,
    responsavel_id: null,
    coordenador_id: null,
    elemento_pep: null,
  },
  {
    nomeProjeto: 'o coalescente - Fuel Gas',
    descricao:
      'Filtro coalescente na linha de sucção do sistema de fuel gas do compressor',
    justificativa:
      'Necessidade de instalação de filtro coalescente na linha de succção do compressor, evitando arreste de liquido e particulados que podem danificar o motor da maquina, por exemplo, com calço hidráulico proveniente de acumulo de condensado na linha ',
    valorTotalPrevisto: 0.0,
    dataInicio: null,
    dataFim: null,
    poloId: 2,
    localId: 2,
    solicitanteId: 2,
    classificacaoId: null,
    divisaoId: null,
    gateId: 2,
    tipoProjetoId: 2,
    demandaId: 1,
    statusId: 1,
    prioridade_id: null,
    complexidade_id: null,
    dataInicioReal: null,
    dataFimReal: null,
    comentarios: null,
    deletado: false,
    item: 79,
    numero: null,
    responsavel_id: null,
    coordenador_id: null,
    elemento_pep: null,
  },
  {
    nomeProjeto: 'o - Descarga do Compressor - EGNA Conceição',
    descricao:
      'Filtro para particulados (Principalmente óleo) na descarga do sistema de compressão do Polo Tucano Sul.',
    justificativa:
      'Necessidade de Filtro para eximir o envio de óleo e outras "sujeiras" provenientes do sistema de compressão da EGNA Conceição. A necessidade de instalação de filtro vem em linha com o que é sugerido para sistemas de compressão que tem por finalidade a entrega de gás para a TAG. ',
    valorTotalPrevisto: 0.0,
    dataInicio: null,
    dataFim: null,
    poloId: 2,
    localId: 2,
    solicitanteId: 2,
    classificacaoId: null,
    divisaoId: null,
    gateId: 2,
    tipoProjetoId: 2,
    demandaId: 1,
    statusId: 1,
    prioridade_id: 3,
    complexidade_id: 3,
    dataInicioReal: null,
    dataFimReal: null,
    comentarios: null,
    deletado: false,
    item: 80,
    numero: null,
    responsavel_id: null,
    coordenador_id: null,
    elemento_pep: null,
  },
  {
    nomeProjeto:
      'o de Análise do Limite de Escoamento das tubulações de entrada de PILAR',
    descricao:
      'Contratação de serviços de engenharia para emissão relatório e validação do limite de escoamento das tubulações entre os Vasos de entrada da Planta e os Compressores de PILAR.',
    justificativa:
      'As tubulações existentes podem não suportar o incremento de vazão com a ampliação da Compressão.',
    valorTotalPrevisto: 0.0,
    dataInicio: null,
    dataFim: null,
    poloId: 1,
    localId: 4,
    solicitanteId: null,
    classificacaoId: null,
    divisaoId: null,
    gateId: 6,
    tipoProjetoId: 1,
    demandaId: 1,
    statusId: 3,
    prioridade_id: 1,
    complexidade_id: 1,
    dataInicioReal: null,
    dataFimReal: null,
    comentarios: null,
    deletado: false,
    item: 81,
    numero: null,
    responsavel_id: null,
    coordenador_id: null,
    elemento_pep: null,
  },
  {
    nomeProjeto: 'Vaso separador de Produção EGNA Conceição',
    descricao: '',
    justificativa:
      'O estudo e posterior aquisição/instalação de PV para controle de pressão no vaso de produção na EGNA Conceição visa ajustar a pressão da planta, otimizando a produção dos poços. A válvula foi retirada pela antiga operadora quando caiu a produção do Polo, no entanto com as intervenções e novo volume de produção, se faz necessário a instalação da mesma para otimização de escoamento dos poços de alta/baixa pressão.',
    valorTotalPrevisto: 0.0,
    dataInicio: null,
    dataFim: null,
    poloId: 2,
    localId: 2,
    solicitanteId: null,
    classificacaoId: null,
    divisaoId: null,
    gateId: 6,
    tipoProjetoId: 1,
    demandaId: 1,
    statusId: 1,
    prioridade_id: 1,
    complexidade_id: 2,
    dataInicioReal: null,
    dataFimReal: null,
    comentarios: null,
    deletado: false,
    item: 82,
    numero: null,
    responsavel_id: null,
    coordenador_id: null,
    elemento_pep: null,
  },
  {
    nomeProjeto: 'Sucção do compressor CUB-03',
    descricao:
      'Estudo de PV para controle de pressão na Sucção do compressor CUB-03 e consequentemente CPIR-01 e CPIR-02',
    justificativa:
      'Ganho de capacidade de compressão de aproximadamente 15 a 25 mil m³/dia.\n\nO estudo e posterior aquisição/instalação de PV para controle de pressão na sucção do compressor CUB-03 visa ajustar a pressão do sistema de sucção de baixa pressão dos compressores CPIR-01, CPIR-02 e CUB-03, otimizando a capacidade de recalque e vazão nominal das 3 máquinas. A válvula foi retirada pela antiga operadora quando caiu a produção do Polo, no entanto, com as intervenções e novo volume de produção, assim como o aumento até a capacidade nominal do sistema de compressão, se faz necessário a instalação da mesma para otimização dos compressores.',
    valorTotalPrevisto: 0.0,
    dataInicio: null,
    dataFim: null,
    poloId: 1,
    localId: 11,
    solicitanteId: 2,
    classificacaoId: null,
    divisaoId: null,
    gateId: 6,
    tipoProjetoId: 1,
    demandaId: 1,
    statusId: 1,
    prioridade_id: null,
    complexidade_id: null,
    dataInicioReal: null,
    dataFimReal: null,
    comentarios: null,
    deletado: false,
    item: 83,
    numero: null,
    responsavel_id: null,
    coordenador_id: null,
    elemento_pep: null,
  },
  {
    nomeProjeto: 'ter - Vaso de produção - EGNA Conceição',
    descricao:
      'Filtro Demister para aumento da eficácia de separação de gotículas e particulados no vaso de produção de EGNA Conceição.',
    justificativa:
      'O estudo e posterior aquisição/instalação de "novo" demister no vaso de produção da EGNA Conceição visa otimizar a recuperação de líquidos, eximindo calço hidráulico no compressor e maior monetização de condensado.\n\nCom o aumento de produção da planta, há a necessidade de revisão de estudo se o equipamento atualmente instalado atende as variaveis atuais de processo. Já foi identificado grande volume de passagem de gotículas, sendo recuperados no scrubber do compressor.',
    valorTotalPrevisto: 0.0,
    dataInicio: null,
    dataFim: null,
    poloId: 2,
    localId: 2,
    solicitanteId: 2,
    classificacaoId: null,
    divisaoId: null,
    gateId: null,
    tipoProjetoId: 1,
    demandaId: 1,
    statusId: 5,
    prioridade_id: 1,
    complexidade_id: 2,
    dataInicioReal: null,
    dataFimReal: null,
    comentarios: null,
    deletado: false,
    item: 84,
    numero: null,
    responsavel_id: null,
    coordenador_id: null,
    elemento_pep: null,
  },
  {
    nomeProjeto: 'do Vaso de Produção e Teste - EGNA Conceição',
    descricao:
      'Ajustes nos Sets dos instrumentos LIT 01 / LV 001A / LV 001B e LIC 002 / LIT 01 dos vasos de produção e teste, respectivamente.',
    justificativa:
      'Melhora na estabilização do processo de separação de líquidos, evitando possível calço hidráulico no compressor decorrentes de frentes grandes de liquido.',
    valorTotalPrevisto: 0.0,
    dataInicio: null,
    dataFim: null,
    poloId: 2,
    localId: 2,
    solicitanteId: 2,
    classificacaoId: null,
    divisaoId: null,
    gateId: null,
    tipoProjetoId: 1,
    demandaId: 1,
    statusId: 5,
    prioridade_id: 1,
    complexidade_id: 2,
    dataInicioReal: null,
    dataFimReal: null,
    comentarios: null,
    deletado: false,
    item: 85,
    numero: null,
    responsavel_id: null,
    coordenador_id: null,
    elemento_pep: null,
  },
  {
    nomeProjeto: 'diretor P16',
    descricao:
      'Elaborar o esboço do plano diretor do P16 contendo documentos mínimos que dê subsídio ao avanço do projeto.\nLocar:\nEstação dos fluidos\nOficinas\nAdm\nGalpões',
    justificativa:
      'Necessidade de reformulação do P16 para dedicar a área ao time de poços.',
    valorTotalPrevisto: 0.0,
    dataInicio: null,
    dataFim: null,
    poloId: 1,
    localId: 15,
    solicitanteId: null,
    classificacaoId: null,
    divisaoId: null,
    gateId: 6,
    tipoProjetoId: 1,
    demandaId: 1,
    statusId: 1,
    prioridade_id: 1,
    complexidade_id: 2,
    dataInicioReal: null,
    dataFimReal: null,
    comentarios: null,
    deletado: false,
    item: 86,
    numero: null,
    responsavel_id: null,
    coordenador_id: null,
    elemento_pep: null,
  },
  {
    nomeProjeto: 'lação Cromatógrafo de Linha - UPGN',
    descricao: '',
    justificativa: '',
    valorTotalPrevisto: 0.0,
    dataInicio: null,
    dataFim: null,
    poloId: 1,
    localId: 9,
    solicitanteId: 2,
    classificacaoId: null,
    divisaoId: null,
    gateId: null,
    tipoProjetoId: 2,
    demandaId: 1,
    statusId: 6,
    prioridade_id: 1,
    complexidade_id: 2,
    dataInicioReal: null,
    dataFimReal: null,
    comentarios: null,
    deletado: false,
    item: 87,
    numero: null,
    responsavel_id: null,
    coordenador_id: null,
    elemento_pep: null,
  },
  {
    nomeProjeto: 'do vaso de teste da EGNA Quererá',
    descricao: '',
    justificativa: '',
    valorTotalPrevisto: 0.0,
    dataInicio: null,
    dataFim: null,
    poloId: 2,
    localId: 17,
    solicitanteId: 2,
    classificacaoId: null,
    divisaoId: null,
    gateId: 6,
    tipoProjetoId: 1,
    demandaId: 1,
    statusId: 1,
    prioridade_id: null,
    complexidade_id: null,
    dataInicioReal: null,
    dataFimReal: null,
    comentarios: null,
    deletado: false,
    item: 88,
    numero: null,
    responsavel_id: null,
    coordenador_id: null,
    elemento_pep: null,
  },
  {
    nomeProjeto: 'EPFU - Vaso de Teste Adicional',
    descricao:
      'emoção de um vaso de teste que está fora de operação na estação de Anambé e instalação na Estação de Furado.',
    justificativa:
      'Atualmente com a quantidade de poços de óleo abertos na estação de Furado está difícil de cumprir com o cronograma dos testes de apropriação e baixíssima possibilidade de realizar testes operacionais.',
    valorTotalPrevisto: 0.0,
    dataInicio: null,
    dataFim: null,
    poloId: 1,
    localId: 16,
    solicitanteId: 2,
    classificacaoId: null,
    divisaoId: null,
    gateId: null,
    tipoProjetoId: 2,
    demandaId: 1,
    statusId: 7,
    prioridade_id: null,
    complexidade_id: null,
    dataInicioReal: null,
    dataFimReal: null,
    comentarios: null,
    deletado: false,
    item: 89,
    numero: 27,
    responsavel_id: null,
    coordenador_id: null,
    elemento_pep: null,
  },
  {
    nomeProjeto: 'Anambé - Bomba dosadora',
    descricao:
      'Instalação de bomba dosadora de desemulsificante na estação de Anambé.\nA bomba já foi comprada se encontra com a equipe de MI na estação de Furado.\nO reservatorio para desemulsificante já está pronto e aguardando na estação de Furado.',
    justificativa:
      'redução da pressão de escoamento no duto e aumento da produção de óleo.',
    valorTotalPrevisto: null,
    dataInicio: null,
    dataFim: null,
    poloId: 1,
    localId: 21,
    solicitanteId: 2,
    classificacaoId: null,
    divisaoId: null,
    gateId: null,
    tipoProjetoId: 2,
    demandaId: 1,
    statusId: 7,
    prioridade_id: 1,
    complexidade_id: 2,
    dataInicioReal: null,
    dataFimReal: null,
    comentarios: null,
    deletado: false,
    item: 90,
    numero: 26,
    responsavel_id: null,
    coordenador_id: null,
    elemento_pep: null,
  },
  {
    nomeProjeto: 'zação das malhas de controle de pressão',
    descricao:
      'Alteração do controle de pressão das linhas de produção de BAIXA / MÉDIA / ALTA para a jusante das PV´s de controle, ou seja, nos vasos depuradores.',
    justificativa:
      'Otimização e maior estabilização das vazões de gás para os compressores',
    valorTotalPrevisto: null,
    dataInicio: null,
    dataFim: null,
    poloId: 1,
    localId: 9,
    solicitanteId: 2,
    classificacaoId: null,
    divisaoId: null,
    gateId: null,
    tipoProjetoId: 2,
    demandaId: 1,
    statusId: 7,
    prioridade_id: 1,
    complexidade_id: null,
    dataInicioReal: null,
    dataFimReal: null,
    comentarios: null,
    deletado: false,
    item: 91,
    numero: null,
    responsavel_id: null,
    coordenador_id: null,
    elemento_pep: null,
  },
  {
    nomeProjeto: 'tura "Meia Água" para retificador de Quererá',
    descricao:
      'Instalação de cobertura metálica para água da chuva no retificador instalado no muro ao lado da sala de controle da EGNA Quererá',
    justificativa:
      'Melhora na proteção do retificador contra possíveis danos provindo de chuvas',
    valorTotalPrevisto: null,
    dataInicio: null,
    dataFim: null,
    poloId: 2,
    localId: 17,
    solicitanteId: 2,
    classificacaoId: null,
    divisaoId: null,
    gateId: null,
    tipoProjetoId: 2,
    demandaId: 1,
    statusId: 7,
    prioridade_id: 1,
    complexidade_id: null,
    dataInicioReal: null,
    dataFimReal: null,
    comentarios: null,
    deletado: false,
    item: 92,
    numero: null,
    responsavel_id: null,
    coordenador_id: null,
    elemento_pep: null,
  },
  {
    nomeProjeto: 'to Piloto - Sistema de Coleta para Tratamento de Poço',
    descricao:
      'Instalação de válvula de 2” no dreno da câmara de Pig, comissionando em sua saída uma linha rígida também de 2”. Essa linha será direcionado para um isotanque, que ficará ao lado da câmara de pig, preferencialmente para o sentido interno da locação.O tratamento do poço será através da válvula de 2” instalada no dreno da câmara de pig ao invés da abertura da portinhola da câmara lançadora, como é realizada atualmente. O fluido será destinado para o isotanque.',
    justificativa:
      'Necessidade urgente de melhoria no sistema de coleta durante os tratamentos dos poços. Já é de conhecimento de todos que, mesmo com a utilização de recipiente coletor (Caixa d’água) no tratamento dos poços há uma perda de fluido para o ambiente, contaminando a locação.',
    valorTotalPrevisto: null,
    dataInicio: null,
    dataFim: null,
    poloId: 2,
    localId: 23,
    solicitanteId: 2,
    classificacaoId: null,
    divisaoId: null,
    gateId: null,
    tipoProjetoId: 2,
    demandaId: 1,
    statusId: 7,
    prioridade_id: 1,
    complexidade_id: null,
    dataInicioReal: null,
    dataFimReal: null,
    comentarios: null,
    deletado: false,
    item: 93,
    numero: null,
    responsavel_id: null,
    coordenador_id: null,
    elemento_pep: null,
  },
  {
    nomeProjeto: 'ão de água produzida Pilar e Furado',
    descricao:
      'Instalação de medidores de água produzida na saída dos TOs de Pilar e Furado.',
    justificativa:
      ' Necessidade da medição para controle operacional da injeção de químicos para otimização do processo e aumento da produção. - Necessidade de informar mensalmente a produção de água à ANP. Hoje é feito por estimativa através de testes de poços. - Necessidade de conhecimento da quantidade real de água produzida diária para estudos de reservatório.',
    valorTotalPrevisto: null,
    dataInicio: null,
    dataFim: null,
    poloId: 1,
    localId: 25,
    solicitanteId: null,
    classificacaoId: null,
    divisaoId: null,
    gateId: null,
    tipoProjetoId: 2,
    demandaId: 1,
    statusId: 7,
    prioridade_id: 1,
    complexidade_id: null,
    dataInicioReal: null,
    dataFimReal: null,
    comentarios: null,
    deletado: false,
    item: 94,
    numero: null,
    responsavel_id: null,
    coordenador_id: null,
    elemento_pep: null,
  },
  {
    nomeProjeto:
      'eio automático na linha de alimentação do gás de selagem proveniente da descarga dos compressores K-201A/B/C para Algás ou Gasalp',
    descricao:
      'Instalar bloqueio automático na linha de alimentação do gás de selagem proveniente da descarga dos compressores K-201A/B/C para Algás ou Gasalp',
    justificativa:
      'Recomendação de Estudo de Riscos - UPGN de Pilar - HAZOP - RL-3202.02-1230-98G-PNE-002.rev.B (R016).',
    valorTotalPrevisto: null,
    dataInicio: null,
    dataFim: null,
    poloId: 1,
    localId: 12,
    solicitanteId: 5,
    classificacaoId: null,
    divisaoId: null,
    gateId: null,
    tipoProjetoId: 2,
    demandaId: 1,
    statusId: 7,
    prioridade_id: 1,
    complexidade_id: null,
    dataInicioReal: null,
    dataFimReal: null,
    comentarios: null,
    deletado: false,
    item: 95,
    numero: null,
    responsavel_id: null,
    coordenador_id: null,
    elemento_pep: null,
  },
  {
    nomeProjeto: 'ma de filtragem do tratamento de água para injeção',
    descricao:
      'Reparo e montagem para adequação dos filtros do sistema de tratamento de água para injeção',
    justificativa:
      'Filtros estão desconectados do processo e com diversos componentes ausentes e/ou necessitando de reparo/substituição, permitindo passagem de objetos para as bombas.',
    valorTotalPrevisto: null,
    dataInicio: null,
    dataFim: null,
    poloId: 1,
    localId: 24,
    solicitanteId: 2,
    classificacaoId: null,
    divisaoId: null,
    gateId: null,
    tipoProjetoId: 2,
    demandaId: 1,
    statusId: 7,
    prioridade_id: 1,
    complexidade_id: 1,
    dataInicioReal: null,
    dataFimReal: null,
    comentarios: null,
    deletado: false,
    item: 96,
    numero: null,
    responsavel_id: null,
    coordenador_id: null,
    elemento_pep: null,
  },
  {
    nomeProjeto: 'Gerador Polo Alagoas',
    descricao:
      'Gerador de energia elétrica movido a óleo diesel para suprimento de carga da UPGN em momentos de falta de energia',
    justificativa:
      'Parada da planta por falta de energia elétrica por conta de constantes falhas da Equatorial',
    valorTotalPrevisto: 6600.0,
    dataInicio: null,
    dataFim: null,
    poloId: 1,
    localId: 9,
    solicitanteId: 2,
    classificacaoId: 6,
    divisaoId: 2,
    gateId: null,
    tipoProjetoId: 2,
    demandaId: 1,
    statusId: 6,
    prioridade_id: 3,
    complexidade_id: 3,
    dataInicioReal: null,
    dataFimReal: null,
    comentarios: null,
    deletado: false,
    item: 48,
    numero: 5,
    responsavel_id: 4,
    coordenador_id: null,
    elemento_pep: null,
  },
  {
    nomeProjeto: 'P16 - Revitalização Estação de Fluidos',
    descricao:
      'Revitalização da Estação de Fluidos, contemplando projetos de tanques de armazenagem de fluidos, sistemas de filtração para processamento de salmouras, sistemas de misturas (agitadores, funis), linhas de escoamento, sistema de controle/monitoramento automático de vazão, e galpões, estruturação de laboratório.',
    justificativa:
      'A Estação de Fluidos de Pilar encontra-se em estado precário e necessita ser revitalizada com o objetivo de torná-la capaz de atender as operações de intervenção de poços do Polo Alagoas.',
    valorTotalPrevisto: 8000000.0,
    dataInicio: null,
    dataFim: null,
    poloId: 1,
    localId: 15,
    solicitanteId: 3,
    classificacaoId: 6,
    divisaoId: 1,
    gateId: 1,
    tipoProjetoId: 2,
    demandaId: 1,
    statusId: 3,
    prioridade_id: 3,
    complexidade_id: 3,
    dataInicioReal: null,
    dataFimReal: null,
    comentarios: null,
    deletado: false,
    item: 5,
    numero: 12,
    responsavel_id: 3,
    coordenador_id: null,
    elemento_pep: 'OGAL.22012.PA',
  },
  {
    nomeProjeto: 'EPPIR - Ar Comprimido',
    descricao:
      'Substituição dos compressores do sistema de ar comprimido de Pilar',
    justificativa:
      'Minimizar riscos de descontinuidades operacionais através do fornecimento de ar de serviço/instrumento em condições adequadas para o processo.',
    valorTotalPrevisto: 1500000.0,
    dataInicio: null,
    dataFim: null,
    poloId: 1,
    localId: 9,
    solicitanteId: 2,
    classificacaoId: 4,
    divisaoId: 1,
    gateId: 1,
    tipoProjetoId: 2,
    demandaId: 1,
    statusId: 3,
    prioridade_id: 1,
    complexidade_id: 2,
    dataInicioReal: null,
    dataFimReal: null,
    comentarios: null,
    deletado: false,
    item: 37,
    numero: 13,
    responsavel_id: null,
    coordenador_id: null,
    elemento_pep: 'OGAL.22013.PA',
  },
  {
    nomeProjeto: 'EPFU - Ar Comprimido',
    descricao:
      'Substituição dos compressores do sistema de ar comprimido de Furado',
    justificativa:
      'Minimizar riscos de descontinuidades operacionais através do fornecimento de ar de serviço/instrumento em condições adequadas para o processo.',
    valorTotalPrevisto: 1000000.0,
    dataInicio: null,
    dataFim: null,
    poloId: 1,
    localId: 16,
    solicitanteId: 2,
    classificacaoId: 4,
    divisaoId: 1,
    gateId: 1,
    tipoProjetoId: 2,
    demandaId: 1,
    statusId: 3,
    prioridade_id: 3,
    complexidade_id: 1,
    dataInicioReal: null,
    dataFimReal: null,
    comentarios: null,
    deletado: false,
    item: 38,
    numero: 14,
    responsavel_id: null,
    coordenador_id: null,
    elemento_pep: 'OGAL.22014.FS',
  },
  {
    nomeProjeto: 'EPFU - Aproveitamento gás TO',
    descricao: 'Aproveitamento do gás que sai do TO para exportação',
    justificativa: 'Otimização do gas produzido evitando desperdicio do mesmo.',
    valorTotalPrevisto: 2000000.0,
    dataInicio: null,
    dataFim: null,
    poloId: 1,
    localId: 16,
    solicitanteId: 2,
    classificacaoId: 5,
    divisaoId: 1,
    gateId: null,
    tipoProjetoId: 2,
    demandaId: 1,
    statusId: 1,
    prioridade_id: 3,
    complexidade_id: 3,
    dataInicioReal: null,
    dataFimReal: null,
    comentarios: null,
    deletado: false,
    item: 20,
    numero: 25,
    responsavel_id: 4,
    coordenador_id: null,
    elemento_pep: 'OGAL.22025.FS',
  },
  {
    nomeProjeto: 'EPFU - Linha para Óleo',
    descricao:
      'Instalação de linha a partir dos tanques de óleo até a baia de carregamento das carretas de Furado possibilitando o transporte da produção através de modal rodoviário',
    justificativa:
      'Antiga linha de carregamento de carretas a partir do óleo proveniente dos tanques de produção de Furado encontra-se descomissionada, desta forma é necessário confecção de novo alinhamento dos tanques até a baia de carregamento das carretas da Estação de Furado para possibilitar o escoamento por modal rodoviário em casos de dificuldades operacionais no oleoduto FU/PIR que atualmente escoa a produção de óleo da Estação.',
    valorTotalPrevisto: 3000000.0,
    dataInicio: null,
    dataFim: null,
    poloId: 1,
    localId: 16,
    solicitanteId: 2,
    classificacaoId: 8,
    divisaoId: 1,
    gateId: 1,
    tipoProjetoId: 2,
    demandaId: 1,
    statusId: 3,
    prioridade_id: 2,
    complexidade_id: 3,
    dataInicioReal: null,
    dataFimReal: null,
    comentarios: null,
    deletado: false,
    item: 16,
    numero: 15,
    responsavel_id: 1,
    coordenador_id: null,
    elemento_pep: 'OGAL.22015.FS',
  },
  {
    nomeProjeto: 'EPFU - Segunda Bomba',
    descricao: 'Base para instalação da 2 bomba de injeção de H2O',
    justificativa: 'Falta de backup para injeção de H2O',
    valorTotalPrevisto: 3000000.0,
    dataInicio: null,
    dataFim: null,
    poloId: 1,
    localId: 16,
    solicitanteId: 2,
    classificacaoId: 8,
    divisaoId: 1,
    gateId: 1,
    tipoProjetoId: 2,
    demandaId: 1,
    statusId: 3,
    prioridade_id: 3,
    complexidade_id: 3,
    dataInicioReal: null,
    dataFimReal: null,
    comentarios: null,
    deletado: false,
    item: 15,
    numero: 16,
    responsavel_id: 4,
    coordenador_id: null,
    elemento_pep: 'OGAL.22016.FS',
  },
  {
    nomeProjeto: 'EPPIR - Área de Resíduos',
    descricao:
      'O projeto reestruturação da área de resíduos da base de Pilar, tem por objetivo adequar a estrutura física de modo a compatibilizar a armazenagem de resíduos com a Legislação ambiente vigente, quanto a segregação, proteção contra intempéries, e proteção das pessoas, a Luz das ABNTNBR 10004/04 – Classificação de resíduos, 12235/92-Armazenamento de resíduos sólidos perigosos e ABNT-NBR 11174/90 – Armazenamento de resíduos não perigosos',
    justificativa: 'A área de resíduos não atende as normas atuais.',
    valorTotalPrevisto: 800000.0,
    dataInicio: null,
    dataFim: null,
    poloId: 1,
    localId: 9,
    solicitanteId: 5,
    classificacaoId: 5,
    divisaoId: 1,
    gateId: 1,
    tipoProjetoId: 2,
    demandaId: 1,
    statusId: 3,
    prioridade_id: 3,
    complexidade_id: 2,
    dataInicioReal: null,
    dataFimReal: null,
    comentarios: null,
    deletado: false,
    item: 22,
    numero: 17,
    responsavel_id: null,
    coordenador_id: null,
    elemento_pep: 'OGAL.22017.PA',
  },
  {
    nomeProjeto: 'Anambé - Separação',
    descricao: 'Estação de separação trifásica Anambé',
    justificativa:
      'Oportunidade de otimização da Produção do campo de Anambé através da separação da separação de água produzida em locação',
    valorTotalPrevisto: 1000000.0,
    dataInicio: null,
    dataFim: null,
    poloId: 1,
    localId: 14,
    solicitanteId: 2,
    classificacaoId: 6,
    divisaoId: 1,
    gateId: 1,
    tipoProjetoId: 2,
    demandaId: 1,
    statusId: 3,
    prioridade_id: 3,
    complexidade_id: 3,
    dataInicioReal: null,
    dataFimReal: null,
    comentarios: null,
    deletado: false,
    item: 9,
    numero: 18,
    responsavel_id: 4,
    coordenador_id: null,
    elemento_pep: 'OGAL.22018.FS',
  },
  {
    nomeProjeto: 'EPPIR - Ampliação Compressão',
    descricao:
      'Ampliação da compressão da UPGN atual para ajuste de capacidade.',
    justificativa:
      'Necessidade de ampliar a capacidade de compressão para a UPGN existente ser capaz de processar o gás natural recebido dos poços.',
    valorTotalPrevisto: 500000.0,
    dataInicio: null,
    dataFim: null,
    poloId: 1,
    localId: 1,
    solicitanteId: 2,
    classificacaoId: 6,
    divisaoId: 2,
    gateId: 1,
    tipoProjetoId: 2,
    demandaId: 1,
    statusId: 3,
    prioridade_id: 3,
    complexidade_id: 2,
    dataInicioReal: null,
    dataFimReal: null,
    comentarios: null,
    deletado: false,
    item: 2,
    numero: 20,
    responsavel_id: 4,
    coordenador_id: null,
    elemento_pep: 'OGAL.22020.PA',
  },
  {
    nomeProjeto: 'EPPIR - Nova UPGN e Compressão',
    descricao:
      'Ampliação da capacidade de processamento da UPGN de Pilar + compressão',
    justificativa:
      'Devido as curvas de produção, a UPGN atual não será capaz de processar a quantidade de gás produzida pelo polo, necessitando de uma ampliação.',
    valorTotalPrevisto: 500000.0,
    dataInicio: null,
    dataFim: null,
    poloId: 1,
    localId: 20,
    solicitanteId: 2,
    classificacaoId: 6,
    divisaoId: 2,
    gateId: 2,
    tipoProjetoId: 2,
    demandaId: 1,
    statusId: 1,
    prioridade_id: 3,
    complexidade_id: 3,
    dataInicioReal: null,
    dataFimReal: null,
    comentarios: null,
    deletado: false,
    item: 1,
    numero: 21,
    responsavel_id: 4,
    coordenador_id: null,
    elemento_pep: 'OGAL.22021.UN',
  },
  {
    nomeProjeto: 'EPPIR - Revitalização injeção de gás',
    descricao:
      'Gas Storage - Restorar, testar e utilizar os dois compressores historicamente utilizado para injeção de gás para começar a injeção de gas em reservatorio denominados para estocagem de gas.',
    justificativa: 'Compressores e linhas para projeto piloto de injeção',
    valorTotalPrevisto: 15000000.0,
    dataInicio: null,
    dataFim: null,
    poloId: 1,
    localId: 9,
    solicitanteId: 6,
    classificacaoId: 6,
    divisaoId: 3,
    gateId: 1,
    tipoProjetoId: 2,
    demandaId: 1,
    statusId: 3,
    prioridade_id: 3,
    complexidade_id: 2,
    dataInicioReal: null,
    dataFimReal: null,
    comentarios: null,
    deletado: false,
    item: 8,
    numero: 6,
    responsavel_id: 3,
    coordenador_id: null,
    elemento_pep: 'OGAL.22006.PA',
  },
  {
    nomeProjeto: 'EPFU - Compressão  (Projeto para 2023)',
    descricao: 'Ampliação do parque de compressão de Furado',
    justificativa:
      'Necessidade de ampliação para que a estação seja capaz de comprimir a nova demanda de gás que será tratada na UPGN de Pilar',
    valorTotalPrevisto: 500000.0,
    dataInicio: null,
    dataFim: null,
    poloId: 1,
    localId: 16,
    solicitanteId: 2,
    classificacaoId: 6,
    divisaoId: 2,
    gateId: 2,
    tipoProjetoId: 2,
    demandaId: 1,
    statusId: 8,
    prioridade_id: 2,
    complexidade_id: 3,
    dataInicioReal: null,
    dataFimReal: null,
    comentarios: null,
    deletado: false,
    item: 4,
    numero: 19,
    responsavel_id: 1,
    coordenador_id: null,
    elemento_pep: 'OGAL.22019.FS',
  },
  {
    nomeProjeto: 'EPPIR - C5+ - Interconexão',
    descricao:
      'Adequação e interligação da infraestrutura do sistema de tanque C5+ e bomba, da estação de óleo de Pilar a baia de carregamento/descarregamento\n\nAs linhas de escoamento já estão comissionadas na estação, assim como bomba de recalque, sendo necessário somente as interconexões para o tanque de C5+ e braço de carregamento.\n\nPosteriormente será avaliado, em conjunto com consultores externos, a necessidade de estabilização do condensado sob responsabilidade do Gustavo Hooper.',
    justificativa:
      'Monetização de subproduto (C5) já produzido no Polo Alagoas, com venda direta para refinarias e beneficiadoras com valor associado maior que do óleo e com incremento na receita. Haverá ainda "saving" em relação a taxa de armazenamento e transporte da Transpetro, tendo em vista o modal a ser transportado.',
    valorTotalPrevisto: 4000000.0,
    dataInicio: null,
    dataFim: null,
    poloId: 1,
    localId: 9,
    solicitanteId: 2,
    classificacaoId: 6,
    divisaoId: 1,
    gateId: 1,
    tipoProjetoId: 2,
    demandaId: 1,
    statusId: 3,
    prioridade_id: 3,
    complexidade_id: 1,
    dataInicioReal: null,
    dataFimReal: null,
    comentarios: null,
    deletado: false,
    item: 11,
    numero: 11,
    responsavel_id: 3,
    coordenador_id: null,
    elemento_pep: 'OGAL.22011.PA',
  },
  {
    nomeProjeto: 'PAL - Escoamento de Poços',
    descricao:
      'Construção das linhas para os poços das intervenções, conforme detalhamento abaixo:\n\nPIR153 - Poço será Injetor de Água após saída da sonda, mas não tem linha de injeção de água.\n\nPIR17 - Poço Injetor de Água, mas não tem linha de injeção de água. \n\nPIR49 - Poço produzirá gás após intervenção, porém não tem linha de produção de gás. \n\nFU-12 - Poço injetor de água, mas não tem linha de injeção. ',
    justificativa:
      'Poços da fila para intervenção com sonda, mas sem linha para injetar água e produzir gás. ',
    valorTotalPrevisto: 500000.0,
    dataInicio: null,
    dataFim: null,
    poloId: 1,
    localId: 5,
    solicitanteId: 2,
    classificacaoId: 6,
    divisaoId: 1,
    gateId: 1,
    tipoProjetoId: 2,
    demandaId: 1,
    statusId: 3,
    prioridade_id: 3,
    complexidade_id: 2,
    dataInicioReal: null,
    dataFimReal: null,
    comentarios: null,
    deletado: false,
    item: 12,
    numero: 23,
    responsavel_id: 4,
    coordenador_id: null,
    elemento_pep: 'OGAL.22023.PA',
  },
  {
    nomeProjeto: 'EPFU - Linha de LGE SCI',
    descricao:
      'Necessária a implantação de sistema fixo de aspersão por espuma para o Tanque TQ-125104 em atendimento a norma NBR 117505-7. O sistema fixo inclui reservatório de água e de LGE, bombas, tubulações, proporcionadores e geradores de espuma.',
    justificativa:
      'A presente proposta de Projeto visa a contratação dos serviços de construção e montagem para conclusão de obra existente (incompleta) do sistema de Combate a Incêndio da Estação Coletora de Furado, Polo Alagoas.',
    valorTotalPrevisto: 400000.0,
    dataInicio: null,
    dataFim: null,
    poloId: 1,
    localId: 16,
    solicitanteId: 5,
    classificacaoId: 3,
    divisaoId: 1,
    gateId: 2,
    tipoProjetoId: 2,
    demandaId: null,
    statusId: 1,
    prioridade_id: 1,
    complexidade_id: 2,
    dataInicioReal: null,
    dataFimReal: null,
    comentarios: null,
    deletado: false,
    item: 30,
    numero: 31,
    responsavel_id: null,
    coordenador_id: null,
    elemento_pep: 'OGAL.22031.FS',
  },
  {
    nomeProjeto: 'Panelas e ETC Catu - Adequação',
    descricao:
      'Retirada das câmaras de pig da estação Panelas, interligação do duto de 10” com duto de 6” e instalação de ETC em Catu',
    justificativa:
      'Sistema necessário para medição e entrega de gás para os clientes bahiagás e TAG.',
    valorTotalPrevisto: 110000000.0,
    dataInicio: null,
    dataFim: null,
    poloId: 2,
    localId: 7,
    solicitanteId: 2,
    classificacaoId: 6,
    divisaoId: 2,
    gateId: 1,
    tipoProjetoId: 2,
    demandaId: 1,
    statusId: 3,
    prioridade_id: 3,
    complexidade_id: 3,
    dataInicioReal: null,
    dataFimReal: null,
    comentarios: null,
    deletado: false,
    item: 3,
    numero: 1,
    responsavel_id: 3,
    coordenador_id: null,
    elemento_pep: 'OGEN.22001.TC',
  },
  {
    nomeProjeto: 'EGNA CON - UEGN Pilota JT',
    descricao: 'Unidade de especificação de gás natural em escala piloto. ',
    justificativa:
      'Necessidade de testar possivel tecnologia para especificação do gás natural de Tucano Sul.',
    valorTotalPrevisto: 6600.0,
    dataInicio: null,
    dataFim: null,
    poloId: 2,
    localId: 2,
    solicitanteId: 2,
    classificacaoId: 6,
    divisaoId: 2,
    gateId: 3,
    tipoProjetoId: 2,
    demandaId: 1,
    statusId: 3,
    prioridade_id: 3,
    complexidade_id: 1,
    dataInicioReal: null,
    dataFimReal: null,
    comentarios: null,
    deletado: false,
    item: 49,
    numero: 2,
    responsavel_id: null,
    coordenador_id: null,
    elemento_pep: 'OGEN.22002.TC',
  },
  {
    nomeProjeto: 'PTS 1 - Escoamento de poços',
    descricao:
      'Substituição das linhas de produção dos poços da intervenção do Polo Tucano Sul para atender as novas vazões e baixas temperaturas esperadas.',
    justificativa:
      ' Necessária substituição de trecho da linha de escoamento dos poços da intervenção do Polo Tucano Sul para atender as novas vazões e temperaturas esperadas.',
    valorTotalPrevisto: 40000000.0,
    dataInicio: null,
    dataFim: null,
    poloId: 2,
    localId: 5,
    solicitanteId: 2,
    classificacaoId: 6,
    divisaoId: 1,
    gateId: 3,
    tipoProjetoId: 2,
    demandaId: 1,
    statusId: 3,
    prioridade_id: 1,
    complexidade_id: 1,
    dataInicioReal: null,
    dataFimReal: null,
    comentarios: null,
    deletado: false,
    item: 27,
    numero: 3,
    responsavel_id: null,
    coordenador_id: null,
    elemento_pep: 'OGEN.22003.TC',
  },
  {
    nomeProjeto: 'EGNA CON - Adequação do SFCI',
    descricao:
      'Após vistoria do CBM-BA (19º Grupamento), registrada pela NOTIFICAÇÃO DE VISTORIA Nº 3326/2021 e respectivo Anexo II Declaração de Compromisso do Interessado, é necessário adequar o sistema fixo de combate à incêndio no que tange a instalação de bomba elétrica (jockey) e seus periféricos e acessórios.',
    justificativa:
      ' A instalação da bomba elétrica (jockey) para garantir as pressões e vazões mínimas para os pontos onde a altura do reservatório elevado não for suficiente para fornecer as vazões e pressões requeridas.',
    valorTotalPrevisto: 13625467.0,
    dataInicio: null,
    dataFim: null,
    poloId: 2,
    localId: 2,
    solicitanteId: 5,
    classificacaoId: 2,
    divisaoId: 1,
    gateId: 1,
    tipoProjetoId: 2,
    demandaId: 1,
    statusId: 3,
    prioridade_id: 3,
    complexidade_id: 2,
    dataInicioReal: null,
    dataFimReal: null,
    comentarios: null,
    deletado: false,
    item: 21,
    numero: 4,
    responsavel_id: null,
    coordenador_id: null,
    elemento_pep: 'OGEN.22004.TC',
  },
  {
    nomeProjeto: 'PTS - UEGN - Projeto Maior',
    descricao:
      'Projeto maior para especificação do gás natural do campo de Tucano sul',
    justificativa: 'Monetização do gás natural proveniente do polo Tucano Sul',
    valorTotalPrevisto: 30000000.0,
    dataInicio: null,
    dataFim: null,
    poloId: 2,
    localId: 2,
    solicitanteId: 2,
    classificacaoId: 6,
    divisaoId: 2,
    gateId: 2,
    tipoProjetoId: 2,
    demandaId: 1,
    statusId: 2,
    prioridade_id: 3,
    complexidade_id: 3,
    dataInicioReal: null,
    dataFimReal: null,
    comentarios: null,
    deletado: false,
    item: 7,
    numero: 10,
    responsavel_id: null,
    coordenador_id: null,
    elemento_pep: 'OGEN.22010.TC',
  },
  {
    nomeProjeto: 'QUE - Bomba Inibidora',
    descricao:
      'Bomba dosadora de inibidor de corrosão para o Gasoduto QUE/CON e CON/PAN',
    justificativa:
      'Verificada pelo time de eng. químicos a necessidade de injeção de inibidor de corrosão no Gasoduto QUE/CON e CON/PAN visando aumento da integridade do duto',
    valorTotalPrevisto: 1000000.0,
    dataInicio: null,
    dataFim: null,
    poloId: 2,
    localId: 17,
    solicitanteId: 2,
    classificacaoId: 5,
    divisaoId: 1,
    gateId: 2,
    tipoProjetoId: 2,
    demandaId: 1,
    statusId: 3,
    prioridade_id: 3,
    complexidade_id: 1,
    dataInicioReal: null,
    dataFimReal: null,
    comentarios: null,
    deletado: false,
    item: 31,
    numero: 22,
    responsavel_id: null,
    coordenador_id: null,
    elemento_pep: 'OGEN.22022.TQ',
  },
  {
    nomeProjeto: 'EGNA CON - Adequação Pressão',
    descricao: '',
    justificativa: '',
    valorTotalPrevisto: 494000.0,
    dataInicio: null,
    dataFim: null,
    poloId: 2,
    localId: 2,
    solicitanteId: 2,
    classificacaoId: 5,
    divisaoId: 1,
    gateId: null,
    tipoProjetoId: 2,
    demandaId: 1,
    statusId: 1,
    prioridade_id: 3,
    complexidade_id: 1,
    dataInicioReal: null,
    dataFimReal: null,
    comentarios: null,
    deletado: false,
    item: 10,
    numero: 24,
    responsavel_id: 3,
    coordenador_id: null,
    elemento_pep: 'OGEN.22024.TC',
  },
  {
    nomeProjeto: 'SMC-12 & CSMC-17 - Trava-Quedas Óleo',
    descricao:
      'Instalar dispositivo de ancoragem para trava quedas retrátil, o qual deve atender as normas NBR 14268/2010 e NBR 16325/2014, fornecido com cabo de aço galvanizado revestido com nylon para locais de trabalho com a atmosfera explosiva para maior durabilidade da mola retrátil e uso de fina corda de nylon para lento recolhimento do cabo que deverá ser fixada no suporte metálico da linha de vida em ponto baixo de fácil acesso para utilização de um trabalhador (100kg) por vez.',
    justificativa:
      'As Estações de São Miguel dos Campo (SMC-12) e Cidade São Miguel dos Campos (CSMC-17) não possuem dispositivo de ancoragem para proteção contra quedas no carregamento de óleo em suas instalações, o colaborador, durante o processo de carregamento do caminhão tanque, faz uso da própria tubulação para afixar o cinturão de segurança tipo paraquedista',
    valorTotalPrevisto: 400000.0,
    dataInicio: null,
    dataFim: null,
    poloId: 1,
    localId: 10,
    solicitanteId: 5,
    classificacaoId: 3,
    divisaoId: 1,
    gateId: 2,
    tipoProjetoId: 2,
    demandaId: null,
    statusId: 1,
    prioridade_id: 3,
    complexidade_id: 1,
    dataInicioReal: null,
    dataFimReal: null,
    comentarios: null,
    deletado: false,
    item: 26,
    numero: 30,
    responsavel_id: null,
    coordenador_id: null,
    elemento_pep: 'OGAL.22030.FS',
  },
  {
    nomeProjeto: 'teste dd',
    descricao:
      'Instalar dispositivo de ancoragem para trava quedas retrátil, o qual deve atender as normas NBR 14268/2010 e NBR 16325/2014, fornecido com cabo de aço galvanizado revestido com nylon para locais de trabalho com a atmosfera explosiva para maior durabilidade da mola retrátil e uso de fina corda de nylon para lento recolhimento do cabo que deverá ser fixada no suporte metálico da linha de vida em ponto baixo de fácil acesso para utilização de um trabalhador (100kg) por vez.',
    justificativa:
      'As Estações de São Miguel dos Campo (SMC-12) e Cidade São Miguel dos Campos (CSMC-17) não possuem dispositivo de ancoragem para proteção contra quedas no carregamento de óleo em suas instalações, o colaborador, durante o processo de carregamento do caminhão tanque, faz uso da própria tubulação para afixar o cinturão de segurança tipo paraquedista',
    valorTotalPrevisto: 400000.0,
    dataInicio: null,
    dataFim: null,
    poloId: 1,
    localId: 10,
    solicitanteId: 5,
    classificacaoId: 3,
    divisaoId: 1,
    gateId: 2,
    tipoProjetoId: 2,
    demandaId: null,
    statusId: 1,
    prioridade_id: 3,
    complexidade_id: 1,
    dataInicioReal: null,
    dataFimReal: null,
    comentarios: null,
    deletado: false,
    item: 26,
    numero: 30,
    responsavel_id: null,
    coordenador_id: null,
    elemento_pep: 'OGAL.22030.FS',
  },
  {
    nomeProjeto: 'TESTE',
    descricao: 'teste',
    justificativa: 'teste',
    valorTotalPrevisto: 50.0,
    dataInicio: null,
    dataFim: null,
    poloId: 1,
    localId: 1,
    solicitanteId: 1,
    classificacaoId: 1,
    divisaoId: 1,
    gateId: 1,
    tipoProjetoId: 1,
    demandaId: 1,
    statusId: 1,
    prioridade_id: 1,
    complexidade_id: 1,
    dataInicioReal: null,
    dataFimReal: null,
    comentarios: 'teste',
    deletado: true,
    item: 10,
    numero: 10,
    responsavel_id: null,
    coordenador_id: null,
    elemento_pep: 'OGAL.777777.PX',
  },
];
