# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node

# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions



name: Complete workflow



on:

  push:

    branches:

      - main

      - master
      
      - development
      
  pull_request:

    branches:

      - main

      - master
      
      - development


jobs:



  build:



    runs-on: ubuntu-latest



    strategy:

      matrix:

        node-version: [14.x]

    steps:

    - uses: actions/checkout@v2



    - name: Use Node.js ${{ matrix.node-version }}

      uses: actions/setup-node@v1

      with:

        node-version: ${{ matrix.node-version }}



    - name: Install dependencies

      run: npm i



    - name: Run build

      run: npm run build



    - name: Deploy application

      if: ${{ github.ref == 'refs/heads/development' || github.ref == 'refs/heads/development' || github.ref == 'refs/heads/master' || github.ref == 'refs/heads/master' }}

      uses: akhileshns/heroku-deploy@v3.12.12

      with:

        heroku_api_key: ${{secrets.HEROKU_API_KEY}}

        heroku_app_name: ${{secrets.HEROKU_APP_NAME}}

        heroku_email: ${{secrets.HEROKU_EMAIL}}

        buildpack: "heroku/nodejs"
